// SPDX-FileCopyrightText: 2026 Minamiyama Kotaro
// SPDX-License-Identifier: AGPL-3.0-only

//! Crate-wide error type. See `docs/design/error.en.md` for the design
//! rationale (in particular, why external-crate errors are type-erased as
//! `Box<dyn std::error::Error + Send + Sync + 'static>` instead of being
//! held as a concrete type).

use std::path::PathBuf;

/// Crate-wide Result alias.
pub type Result<T> = std::result::Result<T, Error>;

/// The common error type used throughout the library. Every module's failure
/// modes, including `parse_workbook`'s `Result::Err`, are consolidated into
/// this type. Marked `#[non_exhaustive]` so future variants can be added
/// without a breaking change.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum Error {
    // --- Phase 1: relationship resolution ---
    /// A required relationship part, e.g. `xl/_rels/workbook.xml.rels`, is
    /// missing from the ZIP.
    #[error("required relationship part not found: {0}")]
    MissingRelationshipPart(String),

    /// The `r:id` referenced by a `<sheet r:id="...">` element in
    /// `workbook.xml` does not exist in the rels part, or the target file the
    /// rels part points to does not exist in the ZIP.
    #[error("dangling relationship reference: r:id={r_id}")]
    DanglingRelationship { r_id: String },

    // --- Phase 2: sanitization ---
    /// The total uncompressed size exceeded the configured limit (Zip Bomb
    /// protection, requirements spec section 2).
    #[error("zip bomb detected: uncompressed size {actual} bytes exceeds limit {limit} bytes")]
    ZipBombDetected { limit: u64, actual: u64 },

    /// A ZIP entry name contains a path traversal sequence that would escape
    /// the extraction directory (Zip Slip protection).
    #[error("path traversal detected in zip entry: {entry_name}")]
    ZipSlipDetected { entry_name: String },

    /// The ZIP archive itself is corrupt, or a required part of the .xlsx
    /// (OPC) package — e.g. `[Content_Types].xml` or `xl/workbook.xml` — is
    /// missing.
    #[error("not a valid .xlsx package: {0}")]
    InvalidPackage(String),

    // --- Phase 3: stream parsing ---
    /// The XML is syntactically invalid (wraps the underlying XML parser
    /// error). `source` does not hold the concrete parser error type (e.g.
    /// `quick_xml::Error`) directly; it is type-erased as `Box<dyn Error>` so
    /// the parser crate `parse/` uses never becomes a public dependency.
    #[error("XML parse error in {path}: {source}")]
    XmlParse {
        path: String,
        #[source]
        source: Box<dyn std::error::Error + Send + Sync + 'static>,
    },

    /// A required element or attribute is missing from the XML (e.g. a `<c>`
    /// element without an `r` attribute).
    #[error("missing required element/attribute `{name}` in {path}")]
    MissingRequiredElement { path: String, name: &'static str },

    /// A `<!DOCTYPE ...>` declaration was detected and rejected unconditionally
    /// (XXE mitigation; generated by `parse/mod.rs`'s `read_event`). None of
    /// OOXML's `_rels`/`workbook.xml`/`sharedStrings.xml`/`styles.xml`/
    /// `sheetX.xml` parts ever carry a DOCTYPE declaration per spec, so this
    /// variant never arises for a legitimate `.xlsx` (security review
    /// Finding 1).
    #[error("DOCTYPE declaration rejected in {path} (XXE defense)")]
    DoctypeRejected { path: String },

    /// `<xdr:grpSp>` nesting depth in a `drawingN.xml` exceeded
    /// `parse::drawing::MAX_GROUP_NESTING_DEPTH`. `parse::drawing`'s
    /// `resolve_grouped_pic` costs O(current nesting depth) per `<xdr:pic>`
    /// resolved, so — the same reasoning as `TooManyMergedRanges` — nesting
    /// depth itself must be bounded independently of the Zip Bomb byte-size
    /// cap: a drawing part with `D` levels of nesting and `N` sibling
    /// pictures at the innermost level costs O(N * D) while costing only
    /// O(N + D) bytes to construct, letting a file of a few tens of MB
    /// (well under the 512 MiB per-entry cap) cause many seconds of
    /// synchronous CPU blocking (security review Finding 1, Issue #71
    /// follow-up).
    #[error("too many nested <xdr:grpSp> groups in {path}: depth {depth} exceeds limit {limit}")]
    TooManyNestedGroups {
        path: String,
        depth: usize,
        limit: usize,
    },

    /// The number of cells materialized into a single `Sheet` (i.e. that
    /// actually reached `Sheet::insert_cell` — a `<c>` with no value, style,
    /// or shared-string reference is dropped for free and never counted)
    /// exceeded `SizeLimits::max_cells_per_sheet`. Checked incrementally as
    /// `parse/worksheet.rs` streams `<c>` elements, not after collecting a
    /// batch (unlike `TooManyMergedRanges`/`TooManyColumnWidthRanges`) — for
    /// cells, the memory cost accrues at the moment of insertion itself
    /// rather than in a separate post-collection step, so checking only
    /// after the fact would already be too late. Guards against the same
    /// class of amplification `TooManyMergedRanges` guards against: the Zip
    /// Bomb byte-size cap alone bounds the XML's raw byte size, not the
    /// `Sheet`'s in-memory footprint after each `<c>` materializes into a
    /// `BTreeMap` entry (Issue #88; see `SizeLimits::max_cells_per_sheet`'s
    /// doc comment for the measured bytes-per-cell this cap is based on).
    #[error("too many cells in {path}: {count} exceeds limit {limit}")]
    TooManyCells {
        path: String,
        count: usize,
        limit: usize,
    },

    // --- Phase 4: analysis and deferred resolution ---
    /// An A1-style cell reference string is invalid (syntax error, numeric
    /// overflow, empty string, etc. — returned by `CellRef::from_a1`).
    #[error("invalid cell reference: {0:?}")]
    InvalidCellRef(String),

    /// A shared string index (referenced via `t="s"`) falls outside the
    /// bounds of the shared string table.
    #[error("shared string index {index} out of bounds (table len={len})")]
    SharedStringIndexOutOfBounds { index: usize, len: usize },

    /// A style ID (index into `cellXfs`) that does not exist was referenced.
    #[error("invalid style id: {0}")]
    InvalidStyleId(u32),

    /// A merged cell range is invalid (overlaps another merged range, or its
    /// start/end coordinates are inverted).
    #[error("invalid merged cell range {start}:{end}: {reason}")]
    InvalidMergedRange {
        start: String,
        end: String,
        reason: String,
    },

    /// The number of `<mergeCell>` entries in a single sheet exceeded
    /// `resolve::merge::MAX_MERGE_REGIONS`. `resolve::merge::resolve`'s
    /// overlap check is O(N^2) in the number of regions, so N itself — not
    /// just the byte size of the XML that declares it, which the Zip Bomb
    /// cap already bounds — must be bounded independently (security review
    /// `docs/security/code-review.md` Finding 1).
    #[error("too many merged cell ranges in one sheet: {count} exceeds limit {limit}")]
    TooManyMergedRanges { count: usize, limit: usize },

    /// A `<col>` range is invalid (overlaps another column-width range).
    /// Mirrors `InvalidMergedRange`'s shape (Issue #39).
    #[error("invalid column width range {min}:{max}: {reason}")]
    InvalidColumnWidthRange { min: u32, max: u32, reason: String },

    /// The number of `<col>` range entries in a single sheet exceeded
    /// `resolve::column_width::MAX_COLUMN_WIDTH_RANGES`. The Zip Bomb
    /// byte-size cap (512 MiB by default) alone permits well over ten
    /// million minimal `<col min="1" max="1" width=".."/>` entries, which
    /// would still cost real CPU time (the O(R log R) sort in
    /// `resolve::column_width::resolve`) and memory (a `Vec` entry per
    /// range) even though that resolution has no O(R^2)/O(R^3) risk of its
    /// own. This cap keeps R itself bounded independently of byte size —
    /// the same reasoning as `TooManyMergedRanges` — while leaving ample
    /// headroom over the handful of ranges a real-world sheet typically has
    /// (Issue #39).
    #[error("too many column width ranges in one sheet: {count} exceeds limit {limit}")]
    TooManyColumnWidthRanges { count: usize, limit: usize },

    /// A hyperlink range is invalid (overlaps another hyperlink range, or
    /// its start/end coordinates are inverted). Mirrors
    /// `InvalidMergedRange`'s shape exactly (Issue #95); overlap is
    /// rejected rather than resolved via a tie-break because
    /// `Sheet::finalize_hyperlinks`'s sweep-line resolution depends on
    /// active ranges at any row having disjoint column spans — the same
    /// precondition `finalize_merges` already relies on from
    /// `resolve::merge`'s own overlap validation.
    #[error("invalid hyperlink range {start}:{end}: {reason}")]
    InvalidHyperlinkRange {
        start: String,
        end: String,
        reason: String,
    },

    /// The number of `<hyperlink>` entries in a single sheet exceeded
    /// `resolve::hyperlink::MAX_HYPERLINKS_PER_SHEET` (Issue #95).
    /// `resolve::hyperlink::resolve`'s overlap check is O(N^2) in the
    /// number of ranges, the same shape as `resolve::merge`'s — so N
    /// itself, not just the XML byte size the Zip Bomb cap already
    /// bounds, must be bounded independently (mirrors
    /// `TooManyMergedRanges`'s reasoning; the cap value is deliberately
    /// the same as `MAX_MERGE_REGIONS` too, reusing its already-measured
    /// cost curve rather than re-deriving one).
    #[error("too many hyperlinks in one sheet: {count} exceeds limit {limit}")]
    TooManyHyperlinks { count: usize, limit: usize },

    // --- Phase 5: JSON generation ---
    /// JSON serialization failed (wraps the error `serde_json` returns).
    /// `source` is type-erased for the same reason as `XmlParse::source`. In
    /// practice `json.rs` always falls back on non-finite floats before ever
    /// handing them to `serde_json`, so no failure is expected to originate
    /// from a value's content; this variant mainly serves as the propagation
    /// path for I/O errors from the `Write` implementation.
    #[error("JSON serialization error: {source}")]
    JsonSerialize {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync + 'static>,
    },

    // --- Common across all phases ---
    /// An I/O error (e.g. the target file cannot be opened or read). `path`
    /// is `Option` because inputs that don't go through a file path (e.g. an
    /// in-memory buffer such as `Cursor<Vec<u8>>`) have no path to report.
    /// When present, it is appended to the `Display` message so the
    /// offending file can be identified from the error text alone.
    #[error("I/O error{}: {source}", io_path_suffix(path))]
    Io {
        path: Option<PathBuf>,
        #[source]
        source: std::io::Error,
    },
}

/// Formats `Error::Io`'s optional `path` as a `Display`-message suffix
/// (empty when `None`).
fn io_path_suffix(path: &Option<PathBuf>) -> String {
    match path {
        Some(p) => format!(" (path: {})", p.display()),
        None => String::new(),
    }
}

/// Converts a path-less I/O error (e.g. from an in-memory buffer) via `?`.
/// Errors with a known path should still be constructed explicitly as
/// `Error::Io { path: Some(..), source }` so the path is reported.
impl From<std::io::Error> for Error {
    fn from(source: std::io::Error) -> Self {
        Error::Io { path: None, source }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::error::Error as _;
    use std::io;

    fn boxed_source(message: &str) -> Box<dyn std::error::Error + Send + Sync + 'static> {
        #[derive(Debug)]
        struct StubError(String);

        impl std::fmt::Display for StubError {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl std::error::Error for StubError {}

        Box::new(StubError(message.to_string()))
    }

    #[test]
    fn display_messages() {
        assert_eq!(
            Error::MissingRelationshipPart("xl/_rels/workbook.xml.rels".into()).to_string(),
            "required relationship part not found: xl/_rels/workbook.xml.rels"
        );

        assert_eq!(
            Error::DanglingRelationship {
                r_id: "rId1".into()
            }
            .to_string(),
            "dangling relationship reference: r:id=rId1"
        );

        assert_eq!(
            Error::ZipBombDetected {
                limit: 100,
                actual: 200
            }
            .to_string(),
            "zip bomb detected: uncompressed size 200 bytes exceeds limit 100 bytes"
        );

        assert_eq!(
            Error::ZipSlipDetected {
                entry_name: "../evil".into()
            }
            .to_string(),
            "path traversal detected in zip entry: ../evil"
        );

        assert_eq!(
            Error::InvalidPackage("missing [Content_Types].xml".into()).to_string(),
            "not a valid .xlsx package: missing [Content_Types].xml"
        );

        assert_eq!(
            Error::XmlParse {
                path: "xl/worksheets/sheet1.xml".into(),
                source: boxed_source("unexpected eof"),
            }
            .to_string(),
            "XML parse error in xl/worksheets/sheet1.xml: unexpected eof"
        );

        assert_eq!(
            Error::MissingRequiredElement {
                path: "xl/worksheets/sheet1.xml".into(),
                name: "r",
            }
            .to_string(),
            "missing required element/attribute `r` in xl/worksheets/sheet1.xml"
        );

        assert_eq!(
            Error::DoctypeRejected {
                path: "xl/sharedStrings.xml".into()
            }
            .to_string(),
            "DOCTYPE declaration rejected in xl/sharedStrings.xml (XXE defense)"
        );

        assert_eq!(
            Error::InvalidCellRef("A0".into()).to_string(),
            "invalid cell reference: \"A0\""
        );

        assert_eq!(
            Error::SharedStringIndexOutOfBounds { index: 5, len: 3 }.to_string(),
            "shared string index 5 out of bounds (table len=3)"
        );

        assert_eq!(
            Error::InvalidStyleId(42).to_string(),
            "invalid style id: 42"
        );

        assert_eq!(
            Error::InvalidMergedRange {
                start: "A1".into(),
                end: "B2".into(),
                reason: "overlaps existing range".into(),
            }
            .to_string(),
            "invalid merged cell range A1:B2: overlaps existing range"
        );

        assert_eq!(
            Error::TooManyMergedRanges {
                count: 20_001,
                limit: 20_000,
            }
            .to_string(),
            "too many merged cell ranges in one sheet: 20001 exceeds limit 20000"
        );

        assert_eq!(
            Error::InvalidColumnWidthRange {
                min: 1,
                max: 5,
                reason: "overlaps another column width range".into(),
            }
            .to_string(),
            "invalid column width range 1:5: overlaps another column width range"
        );

        assert_eq!(
            Error::TooManyColumnWidthRanges {
                count: 2_001,
                limit: 2_000,
            }
            .to_string(),
            "too many column width ranges in one sheet: 2001 exceeds limit 2000"
        );

        assert_eq!(
            Error::TooManyNestedGroups {
                path: "xl/drawings/drawing1.xml".into(),
                depth: 65,
                limit: 64,
            }
            .to_string(),
            "too many nested <xdr:grpSp> groups in xl/drawings/drawing1.xml: depth 65 exceeds limit 64"
        );

        assert_eq!(
            Error::TooManyCells {
                path: "xl/worksheets/sheet1.xml".into(),
                count: 5_000_001,
                limit: 5_000_000,
            }
            .to_string(),
            "too many cells in xl/worksheets/sheet1.xml: 5000001 exceeds limit 5000000"
        );

        assert_eq!(
            Error::JsonSerialize {
                source: boxed_source("trailing comma"),
            }
            .to_string(),
            "JSON serialization error: trailing comma"
        );

        assert_eq!(
            Error::Io {
                path: Some(PathBuf::from("book.xlsx")),
                source: io::Error::new(io::ErrorKind::NotFound, "no such file"),
            }
            .to_string(),
            "I/O error (path: book.xlsx): no such file"
        );

        assert_eq!(
            Error::Io {
                path: None,
                source: io::Error::new(io::ErrorKind::NotFound, "no such file"),
            }
            .to_string(),
            "I/O error: no such file"
        );
    }

    #[test]
    fn io_error_converts_via_from_with_no_path() {
        let io_err = io::Error::new(io::ErrorKind::PermissionDenied, "denied");
        let err: Error = io_err.into();
        match &err {
            Error::Io { path, source } => {
                assert_eq!(*path, None);
                assert_eq!(source.to_string(), "denied");
            }
            other => panic!("expected Error::Io, got {other:?}"),
        }
        assert_eq!(err.to_string(), "I/O error: denied");
    }

    #[test]
    fn from_io_error_propagates_via_question_mark() {
        fn fallible() -> Result<()> {
            Err(io::Error::other("boom"))?;
            Ok(())
        }

        let err = fallible().unwrap_err();
        assert!(matches!(err, Error::Io { path: None, .. }));
    }

    #[test]
    fn source_chain_is_preserved() {
        let xml_err = Error::XmlParse {
            path: "xl/worksheets/sheet1.xml".into(),
            source: boxed_source("unexpected eof"),
        };
        assert_eq!(xml_err.source().unwrap().to_string(), "unexpected eof");

        let json_err = Error::JsonSerialize {
            source: boxed_source("trailing comma"),
        };
        assert_eq!(json_err.source().unwrap().to_string(), "trailing comma");

        let io_err = Error::Io {
            path: None,
            source: io::Error::new(io::ErrorKind::PermissionDenied, "denied"),
        };
        assert_eq!(io_err.source().unwrap().to_string(), "denied");
    }
}
